#!/bin/bash
# 환경변수(Codex/CI 비밀값)로 env.yaml 만들기 — 비밀값을 git 에 넣지 않기 위함.
#   필요한 변수: TELEGRAM_BOT_TOKEN ANTHROPIC_API_KEY DISCORD_BOT_TOKEN (+ 아래 목록 중 있는 것)
#   bash tools/make_env.sh > env.yaml
set -e
: "${TELEGRAM_BOT_TOKEN:?}" "${ANTHROPIC_API_KEY:?}"
q() { printf '%s: "%s"\n' "$1" "${!1}"; }
for k in SHEET_ID ANTHROPIC_API_KEY CLAUDE_MODEL BOT_TZ TELEGRAM_BOT_TOKEN ADMIN_CHAT_ID SALES_CHAT_IDS \
         TELEGRAM_WEBHOOK_SECRET DISCORD_BOT_TOKEN DISCORD_APP_ID DISCORD_PUBLIC_KEY DISCORD_GUILD_ID \
         DISCORD_MANAGER_ROLE_IDS DISCORD_URGENT_ROLE_ID DISCORD_REQUESTS_CHANNEL_ID DISCORD_LOG_CHANNEL_ID \
         DISCORD_CONFIRM_CHANNEL_ID DISCORD_REPORTS_CHANNEL_ID DISCORD_AI_MODEL DISCORD_WEBHOOK_URL \
         TALKBRIDGE_BRAND_KEY TALKBRIDGE_AGENT_KEY TALKBRIDGE_WHSEC BOT_BASE_URL; do
  q "$k"
done
